export default{
  "login": "iJCode1",
  "id": 50086105,
  "node_id": "MDQ6VXNlcjUwMDg2MTA1",
  "avatar_url": "https://avatars.githubusercontent.com/u/50086105?v=4",
  "gravatar_id": "",
  "url": "https://api.github.com/users/iJCode1",
  "html_url": "https://github.com/iJCode1",
  "followers_url": "https://api.github.com/users/iJCode1/followers",
  "following_url": "https://api.github.com/users/iJCode1/following{/other_user}",
  "gists_url": "https://api.github.com/users/iJCode1/gists{/gist_id}",
  "starred_url": "https://api.github.com/users/iJCode1/starred{/owner}{/repo}",
  "subscriptions_url": "https://api.github.com/users/iJCode1/subscriptions",
  "organizations_url": "https://api.github.com/users/iJCode1/orgs",
  "repos_url": "https://api.github.com/users/iJCode1/repos",
  "events_url": "https://api.github.com/users/iJCode1/events{/privacy}",
  "received_events_url": "https://api.github.com/users/iJCode1/received_events",
  "type": "User",
  "site_admin": false,
  "name": "Joel Dominguez Merino",
  "company": null,
  "blog": "",
  "location": "Toluca",
  "email": null,
  "hireable": null,
  "bio": "Estudiante de Ingeniería en Sistemas Computacionales.",
  "twitter_username": "iJCode1",
  "public_repos": 75,
  "public_gists": 0,
  "followers": 29,
  "following": 20,
  "created_at": "2019-04-28T21:04:34Z",
  "updated_at": "2022-10-02T12:56:38Z"
}